# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UNTZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UNTZ

pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage', '~> 3.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'ReachabilitySwift', '~> 3'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage', '~>3.8'
end
