# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UNTZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UNTZ

pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage', '~> 3.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'ReachabilitySwift', '~> 3'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage', '~>3.8'
pod 'Hex'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
